### ISSUE TITLE
Will there be an Angular version?

### ISSUE THREAD

**Issue by mackelito** [opbeat/opbeat-angular#12]
Please remove if this should not be asked here :)

**Comment by AugusDogus** [comment]
Over a month has gone by without any word. Can we please get an answer on if this is planned?

**Comment by hmdhk** [comment]
Hi @mackelito , @AugusDogus ,

Thanks for reaching out and sorry about the slow response!

As you know Opbeat was acquired by Elastic last year and so far we have been focusing on integrating our product into elastic stack. We have just released our first JavaScript integration into alpha. You can find the repo [here](https://github.com/elastic/apm-agent-js-base) and also please see our [Getting Started](https://www.elastic.co/guide/en/apm/get-started/current/index.html) guide. This release is framework independent and provides error logging and basic performance monitoring features.

Going forward we will be developing new integrations as a part of elastic stack (instead of Opbeat), However I can't provide a timeline for an Angular integration yet.

Please don't hesitate to open an issue if you have any questions.

Cheers,
Hamid

**Comment by AugusDogus** [comment]
Thanks for the reply! I figured this was the case, but it's nice to be certain.
